### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Tiamu322** [NovaEngineering-Source/ModularMachinery-Community-Edition#109]
It only works for me on the version 1.12.2-1.11.1-r55.  All pro versions cause me to crash. This is a pre8 from github.

[20:04:45] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[20:04:45] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[20:04:45] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[20:04:45] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2860 for Minecraft 1.12.2 loading
[20:04:45] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_401, running on Windows 10:amd64:10.0, installed at C:\Users\aleks\AppData\Roaming\.minecraft\java\jre1.8.0_251
[20:04:46] [main/INFO] [FML]: Searching C:\Users\aleks\AppData\Roaming\.minecraft\mods for mods
[20:04:46] [main/INFO] [FML]: Searching C:\Users\aleks\AppData\Roaming\.minecraft\mods\1.12.2 for mods
[20:04:46] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in appliedenergistics2-rv6-stable-7-extended_life-v0.55.21.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:04:46] [main/WARN] [FML]: The coremod AE2ELCore (appeng.core.AE2ELCore) is not signed!
[20:04:46] [main/INFO] [FML]: Loading tweaker guichaguri.betterfps.tweaker.BetterFpsTweaker from BetterFps-1.4.8.jar
[20:04:46] [main/INFO] [FML]: Loading tweaker codechicken.asm.internal.Tweaker from ChickenASM-1.12-1.0.2.7.jar
[20:04:46] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in CTM-MC1.12.2-0.3.3.22.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:04:46] [main/WARN] [FML]: The coremod team.chisel.ctm.client.asm.CTMCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:04:46] [main/WARN] [FML]: The coremod CTMCorePlugin (team.chisel.ctm.client.asm.CTMCorePlugin) is not signed!
[20:04:46] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in cxlibrary-1.12.1-1.6.1.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:04:46] [main/WARN] [FML]: The coremod cubex2.cxlibrary.CoreModLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:04:46] [main/WARN] [FML]: The coremod CXLibraryCore (cubex2.cxlibrary.CoreModLoader) is not signed!
[20:04:46] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in foamfix-0.10.5-1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:04:46] [main/WARN] [FML]: The coremod pl.asie.foamfix.coremod.FoamFixCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:04:46] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Forgelin-1.8.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:04:46] [main/WARN] [FML]: The coremod net.shadowfacts.forgelin.preloader.ForgelinPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:04:46] [main/WARN] [FML]: The coremod ForgelinPlugin (net.shadowfacts.forgelin.preloader.ForgelinPlugin) is not signed!
[20:04:46] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in GrandGearPass-client.1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:04:46] [main/ERROR] [FML]: Coremod HookLoaderCore: Unable to class load the plugin ru.vizzi.alamine.hooks.HookLoaderCore
java.lang.ClassNotFoundException: ru.vizzi.alamine.hooks.HookLoaderCore
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_401]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_401]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_401]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_401]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_401]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:527) [forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) [forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) [forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) [forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:81) [forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:42) [forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:141) [forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[20:04:46] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in InventoryTweaks-1.64+dev.146.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:04:46] [main/WARN] [FML]: The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:04:46] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from LagGoggles-FAT-1.12.2-4.9.jar
[20:04:46] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Mekanism-Community-Edition-1.12.2-9.12.7-Core.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:04:46] [main/WARN] [FML]: The coremod mekanism.coremod.MekanismCoremod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:04:46] [main/WARN] [FML]: The coremod MekanismCoremod (mekanism.coremod.MekanismCoremod) is not signed!
[20:04:46] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in ModularMachinery-CE-2.0.0-pre8.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:04:46] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.RuntimeException: An error occurred trying to configure the Minecraft home at C:\Users\aleks\AppData\Roaming\.minecraft for Forge Mod Loader
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:111) ~[forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:81) ~[forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:42) ~[forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:141) ~[forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoClassDefFoundError: zone/rong/mixinbooter/IEarlyMixinLoader
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_401]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_401]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_401]
	at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.8.0_401]
	at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.8.0_401]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_401]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_401]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_401]
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_401]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_401]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_401]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_401]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_401]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:527) ~[forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) ~[forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) ~[forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) ~[forge-1.12.2-14.23.5.2860.jar:?]
	... 5 more
Caused by: java.lang.ClassNotFoundException: zone.rong.mixinbooter.IEarlyMixinLoader
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_401]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_401]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_401]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_401]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_401]
	at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.8.0_401]
	at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.8.0_401]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_401]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_401]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_401]
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_401]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_401]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_401]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_401]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_401]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:527) ~[forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) ~[forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) ~[forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) ~[forge-1.12.2-14.23.5.2860.jar:?]
	... 5 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_401]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_401]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_401]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_401]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_401]
	at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.8.0_401]
	at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.8.0_401]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_401]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_401]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_401]
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_401]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_401]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_401]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_401]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_401]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:527) ~[forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) ~[forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) ~[forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) ~[forge-1.12.2-14.23.5.2860.jar:?]
	... 5 more
[20:04:46] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[20:04:46] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[20:04:46] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[20:04:46] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[20:04:46] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
[20:04:46] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[20:04:46] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by KasumiNova** [comment]
As of version 2.0.0, the mixinbooter needs to be installed.
